### ISSUE TITLE
[Usersnap] its giving  Uncaught RegerenceError: string is not defined

### ISSUE THREAD

**Issue by epicodus-it** [epicodus-curriculum/intro-full-stack#22]
Usersnap feedback [5033](https://app.usersnap.com/l/feedback/8c9e2ad0-8c2c-4b09-8c71-2e8f5a68dee7?utm_medium=integration&utm_campaign=integration&utm_content=open):

URL: https://full-time.learnhowtoprogram.com/introduction-to-programming/javascript-and-web-browsers/functions

Text: its giving  Uncaught RegerenceError: string is not defined

Screenshot: https://resources.usersnap.com/company/e2ef6bfd-aefd-493c-be03-42655e35a11f/datapoint_screenshot/64b6cbc3-f4eb-4a3d-9821-79819bfe12fe-annotated_4d95d276-dc05-4f9d-b11e-43cdcd344355.png?etag=c7cfb7e2465526657530fcbf65fadcab

**Comment by erik-t-irgens** [comment]
I went ahead and changed the original function that referenced `string` to reference the parameter string instead `stringParam`. 

Fixed!
