### ISSUE TITLE
[Usersnap] It looks like the end paren is missing in "friend! in the concatenation practice.

### ISSUE THREAD

**Issue by epicodus-it** [epicodus-curriculum/intro-full-stack#23]
Usersnap feedback [5034](https://app.usersnap.com/l/feedback/911bba6d-9a0b-4648-a715-9a117d84273f?utm_medium=integration&utm_campaign=integration&utm_content=open):

URL: https://full-time.learnhowtoprogram.com/introduction-to-programming/javascript-and-web-browsers/practice-string-and-number-methods

Text: It looks like the end paren is missing in "friend! in the concatenation practice.

Screenshot: https://resources.usersnap.com/company/e2ef6bfd-aefd-493c-be03-42655e35a11f/datapoint_screenshot/5838a049-ba04-4eda-af47-0b23ba3991d7-annotated_77f7877a-9d4c-4876-8d32-89ca573873b8.png?etag=c4a3b250a402eaa5847e031e24f29cce

**Comment by mgoren** [comment]
fixed
