### ISSUE TITLE
[Usersnap] The link referenced for "Ally Skills Workshop handout" does not appear to work.  https://files.frameshiftconsulting.com/Ally%20Skills%20Workshop%20handout%20-%20US.pdf  Looking at the webpage, it appears that this is because the original link is actual...

### ISSUE THREAD

**Issue by epicodus-it** [epicodus-curriculum/intro-full-stack#26]
Usersnap feedback [5041](https://app.usersnap.com/l/feedback/eea8c69b-0853-44c4-8c55-fab497a7d786?utm_medium=integration&utm_campaign=integration&utm_content=open):

URL: https://full-time.learnhowtoprogram.com/introduction-to-programming/javascript-and-web-browsers/homework-identifying-and-preventing-microaggressions

Text: The link referenced for "Ally Skills Workshop handout" does not appear to work.  https://files.frameshiftconsulting.com/Ally%20Skills%20Workshop%20handout%20-%20US.pdf  Looking at the webpage, it appears that this is because the original link is actual...

Screenshot: https://resources.usersnap.com/company/e2ef6bfd-aefd-493c-be03-42655e35a11f/datapoint_screenshot/634db742-1f60-466e-9a6f-3396485134bb-annotated_03ca7f16-fb5e-4287-a777-073bd70b47f3.png?etag=deb07b7c90b7f740e2e7a16ec7b18cf1

**Comment by mgoren** [comment]
fixed
