### ISSUE TITLE
[Usersnap] "Object types are written un UpperCamelCase" should be "Object types are written in UpperCamelCase"

### ISSUE THREAD

**Issue by epicodus-it** [epicodus-curriculum/intro-full-stack#28]
Usersnap feedback [5043](https://app.usersnap.com/l/feedback/7db908bf-495d-4a5c-8711-ecf6100bc635?utm_medium=integration&utm_campaign=integration&utm_content=open):

URL: https://full-time.learnhowtoprogram.com/introduction-to-programming/javascript-and-web-browsers/understanding-web-apis-interfaces-object-types-and-inheritance

Text: "Object types are written un UpperCamelCase" should be "Object types are written in UpperCamelCase"

Screenshot: https://resources.usersnap.com/company/e2ef6bfd-aefd-493c-be03-42655e35a11f/datapoint_screenshot/31729036-e829-4ae8-9340-54965c5eba81-annotated_f6737ebb-7a2a-4d37-a963-a943f05f98c8.png?etag=5eae5dbc8df3f8d1f3d15c3eeca5828e

**Comment by mgoren** [comment]
fixed
