### ISSUE TITLE
[Usersnap] The links for String.prototype.concat() and Array.prototype.concat() are reversed. String takes you to the Array page and Array takes you to the String page

### ISSUE THREAD

**Issue by epicodus-it** [epicodus-curriculum/intro-full-stack#31]
Usersnap feedback [5053](https://app.usersnap.com/l/feedback/13f2300c-3153-4dc9-b465-77404b70952b?utm_medium=integration&utm_campaign=integration&utm_content=open):

URL: https://full-time.learnhowtoprogram.com/introduction-to-programming/arrays-and-looping/the-basics-of-prototypes

Text: The links for String.prototype.concat() and Array.prototype.concat() are reversed. String takes you to the Array page and Array takes you to the String page

Screenshot: https://resources.usersnap.com/company/e2ef6bfd-aefd-493c-be03-42655e35a11f/datapoint_screenshot/39547e73-823d-46ec-843f-912e1d4e2704-annotated_675c1d12-0287-4555-9601-60793da4e602.png?etag=c5d27126c7105825113960184361be0f

**Comment by mgoren** [comment]
fixed
